  version: '3.8'

  services:
    nghenhac-app:
      build:
        context: .
        dockerfile: Dockerfile

      container_name: nghenhac-app
      restart: always

      ports:
        - "20080:8080"

      env_file:
        - .env

      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s

      extra_hosts:
        - "host.docker.internal:host-gateway"